Description: Template for EC2 instance with Cloudshirt

Resources:
  CloudShirtEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
        BlockDeviceMappings: 
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true 
            VolumeType: gp3
            VolumeSize: 30
            Encrypted: "true" 
        InstanceType: t2.micro 
        ImageId: ami-0ebfd941bbafe70c6 #Needs to be AMI 2023
        KeyName: vockey 
        SecurityGroupIds: 
          - !ImportValue  CloudShirt:SecurityGroupId 
        SubnetId: !ImportValue CloudShirt:PublicSubnet1 # Deploy the instance in the public subnet in AZ.
        Tags:
          - Key: Name
            Value: cloudshirt-instance
        UserData: 
          Fn::Base64: 
            !Sub |
              #!/bin/bash
              sudo yum update
              sudo yum upgrade -y
              sudo yum install -y git
              sudo yum install -y aspnetcore-runtime-6.0
              sudo yum install -y dotnet-sdk-6.0
              sudo dnf update dotnet6.0 --releasever 2023.1.20230719
              sudo cd /root
              git clone https://github.com/looking4ward/CloudShirt.git
              sudo cd CloudShirt/src/Web
              sudo dotnet publish -c Release -o ../../../release
              sudo cd ../../../release
              sudo dotnet Web.dlle

Outputs:
  EC2InstanceId:
    Description: "The Instance ID of the EC2 instance"
    Value: !Ref CloudShirtEC2Instance
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", EC2InstanceId ] ] # Fancy way of making the exported variable called "MyBase:Var"
