Resources:
  CloudShirtS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: CloudShirtS3Bucket
      VersioningConfiguration:
        Status: Disabled

Outputs:
  S3BucketName:
    Description: "The name of the S3 bucket"
    Value: !Ref CloudShirtS3Bucket
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", S3BucketName ] ] # Fancy way of making the exported variable called "MyBase:Var"
      
  S3BucketArn:
    Description: "The ARN of the S3 bucket"
    Value: !GetAtt CloudShirtS3Bucket.Arn
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", S3BucketArn ] ] # Fancy way of making the exported variable called "MyBase:Var"
