Description: Template for EC2 instance with Cloudshirt

Resources:
  CloudShirtEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
        BlockDeviceMappings: 
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true 
            VolumeType: gp3
            VolumeSize: 30
            Encrypted: "true" 
        InstanceType: t2.micro 
        ImageId: ami-0ebfd941bbafe70c6 #Needs to be AMI 2023
        KeyName: vockey 
        SecurityGroupIds: 
          - !ImportValue  CloudShirt:SecurityGroupId 
        SubnetId: !ImportValue CloudShirt:PublicSubnet1 # Deploy the instance in the public subnet in AZ.
        Tags:
          - Key: Name
            Value: cloudshirt-instance
        UserData: 
          Fn::Base64: 
            !Sub |
              #!/bin/bash
              sudo yum -y install httpd
              sudo yum -y install git 
              sudo yum -y install libunwind libicu  
              curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?LinkID=835019  
              sudo mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet  
              sudo ln -s /opt/dotnet/dotnet /usr/local/bi 

Outputs:
  EC2InstanceId:
    Description: "The Instance ID of the EC2 instance"
    Value: !Ref CloudShirtEC2Instance
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", EC2InstanceId ] ] # Fancy way of making the exported variable called "MyBase:Var"
