# Base image
FROM mcr.microsoft.com/dotnet/aspnet:8.0

# Install necessary packages, set up Microsoft repository, and install .NET 6.0 runtime and SDK
RUN apt-get update -y && \
    apt-get install -y wget gnupg software-properties-common && \
    wget https://packages.microsoft.com/config/debian/$(lsb_release -rs)/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install -y git aspnetcore-runtime-6.0 dotnet-sdk-6.0 && \
    rm -rf /var/lib/apt/lists/*  # Clean up APT cache

# Clone the repository and prepare configuration
RUN git clone https://github.com/looking4ward/CloudShirt.git /root/CloudShirt && \
    sed -i 's/Server.*CatalogDb;/Server={{ rds_ip }},1433;User ID=admin;Password=CloudShirt123;Initial Catalog=Microsoft.eShopOnWeb.CatalogDb;/' /root/CloudShirt/src/Web/appsettings.json && \
    sed -i 's/Server.*Identity;/Server={{ rds_ip }},1433;User ID=admin;Password=CloudShirt123;Initial Catalog=Microsoft.eShopOnWeb.Identity;/' /root/CloudShirt/src/Web/appsettings.json

# Set working directory to the project path and publish the application
WORKDIR /root/CloudShirt/src/Web
RUN dotnet publish -c Release -o /root/release
ENV ASPNETCORE_ENVIRONMENT=Development
# Expose port and set the entry point
EXPOSE 80
CMD ["dotnet", "/root/release/Web.dll", "--urls", "http://0.0.0.0:80"]

# Expose port and start the application
# EXPOSE 80
