Description: Template for EC2 instance with Cloudshirt

Resources:
  CloudShirtLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: CloudShirtLaunchTemplate
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              DeleteOnTermination: true
              VolumeType: gp3
              VolumeSize: 30
              Encrypted: "true"
        InstanceType: t2.micro
        ImageId: ami-0ebfd941bbafe70c6
        IamInstanceProfile:
          Name: LabInstanceProfile
        KeyName: vockey
        SecurityGroupIds:
          - !ImportValue CloudShirt:SecurityGroupId
        UserData: 
          Fn::Base64: !Sub 
          - |
            #!/bin/bash
            sudo sudo yum update -y
            sudo sudo yum upgrade -y
            sudo sudo yum install -y docker

            sudo usermod -a -G docker ec2-user

            sudo service docker start
            sudo systemctl enable docker

            sudo chmod 666 /var/run/docker.sock

            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 093215643118.dkr.ecr.us-east-1.amazonaws.com
            JOIN_TOKEN=$(aws ssm get-parameter --name /swarm/joinToken --query "Parameter.Value" --output text)
            docker swarm join --token $JOIN_TOKEN ${MANAGERIP}:2377

          - MANAGERIP:
              Fn::ImportValue: CloudShirtBuildServer:PrivateIp
  
  CloudShirtASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref CloudShirtLaunchTemplate
        Version: !GetAtt CloudShirtLaunchTemplate.LatestVersionNumber
      DesiredCapacity: '3'
      MaxSize: '10'
      MinSize: '1'
      VPCZoneIdentifier: 
        - !ImportValue CloudShirt:PublicSubnet1
        - !ImportValue CloudShirt:PublicSubnet2
      TargetGroupARNs:
        - !Ref CloudShirtTargetGroup
  
  CloudShirtASGUp: # Deze schaalt hem omhoog
    Type: "AWS::AutoScaling::ScheduledAction"
    Properties: 
      AutoScalingGroupName: !Ref CloudShirtASG
      DesiredCapacity: '9' 
      MinSize: '1' 
      MaxSize: '10' 
      Recurrence: "0 22 * * *" # UTC-4 (for 6 PM Eastern Time)
  
  CloudShirtASGDown: # Deze schaalt hem af
    Type: "AWS::AutoScaling::ScheduledAction"
    Properties:
      AutoScalingGroupName: !Ref CloudShirtASG
      DesiredCapacity: '2' 
      MinSize: '1' 
      MaxSize: '10' 
      Recurrence: "0 0 * * *" # UTC-4 (for 8 PM Eastern Time)
  
  CloudShirtLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: CloudShirt
      Subnets:
        - !ImportValue CloudShirt:PublicSubnet1
        - !ImportValue CloudShirt:PublicSubnet2
      SecurityGroups:
        - !ImportValue CloudShirt:SecurityGroupId
      Tags:
        - Key: Name
          Value: CloudShirtLB

  CloudShirtLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref CloudShirtLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref CloudShirtTargetGroup

  CloudShirtTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: CloudShirtTargetGroup
      VpcId: !ImportValue CloudShirt:VPC
      Port: 80
      Protocol: HTTP
