Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0  # Example for Amazon Linux 2
      KeyName: vockey
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref MySubnet
          GroupSet:
            - !Ref MySecurityGroup

Outputs:
  EC2InstanceId:
    Description: "The Instance ID of the EC2 instance"
    Value: !Ref MyEC2Instance
    Export:
      Name: !Sub "${AWS::StackName}-EC2InstanceId"
      
  EC2PublicIP:
    Description: "The public IP address of the EC2 instance"
    Value: !GetAtt MyEC2Instance.PublicIp
    Export:
      Name: !Sub "${AWS::StackName}-EC2PublicIP"
