Resources:
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  MyNATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt MyEIP.AllocationId
      SubnetId: !Ref MySubnet
      ConnectivityType: public

Outputs:
  NATGatewayId:
    Description: "The ID of the NAT Gateway"
    Value: !Ref MyNATGateway
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", NATGatewayId ] ] # Fancy way of making the exported variable called "MyBase:Var"
      
  NATGatewayEIP:
    Description: "The EIP associated with the NAT Gateway"
    Value: !Ref MyEIP
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", NATGatewayEIP ] ] # Fancy way of making the exported variable called "MyBase:Var"
