Resources:
  MyPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: MyPrivateSubnet

Outputs:
  PrivateSubnetId:
    Description: "The ID of the private subnet"
    Value: !Ref MyPrivateSubnet
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", PrivateSubnetId ] ] # Fancy way of making the exported variable called "MyBase:Var"
