Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-s3-bucket-example
      VersioningConfiguration:
        Status: Enabled

Outputs:
  S3BucketName:
    Description: "The name of the S3 bucket"
    Value: !Ref MyS3Bucket
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", S3BucketName ] ] # Fancy way of making the exported variable called "MyBase:Var"
      
  S3BucketArn:
    Description: "The ARN of the S3 bucket"
    Value: !GetAtt MyS3Bucket.Arn
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", S3BucketArn ] ] # Fancy way of making the exported variable called "MyBase:Var"
