Resources:
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: MyTopic
      TopicName: MySNSTopic

Outputs:
  SNSTopicArn:
    Description: "The ARN of the SNS topic"
    Value: !Ref MySNSTopic
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", SNSTopicArn ] ] # Fancy way of making the exported variable called "MyBase:Var"

  SNSTopicName:
    Description: "The name of the SNS topic"
    Value: !GetAtt MySNSTopic.TopicName
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", SNSTopicName ] ] # Fancy way of making the exported variable called "MyBase:Var"
