Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC

Outputs:
  VPCId:
    Description: "The ID of the VPC"
    Value: !Ref MyVPC
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", VPCId ] ] # Fancy way of making the exported variable called "MyBase:Var"

  VPCCidr:
    Description: "The CIDR block of the VPC"
    Value: !GetAtt MyVPC.CidrBlock
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", VPCCidr ] ] # Fancy way of making the exported variable called "MyBase:Var"