# Base immage
FROM python:3.9.4-slim-buster
# Updates uitvoeren en directory maken voor de Credentials
RUN apt-get update; \
    apt-get upgrade; \
    apt-get install -y gcc python3; \
    apt-get install -y python3-pip; \
    apt-get clean all; \
    apt-get install docker
    mkdir /root/gcp-credentials
# Instaleer curl
RUN apt-get update && apt-get install -y \
    curl \
    gettext-base \
    && rm -rf /var/lib/apt/lists/*
# Instaleer meer curl
RUN apt-get update && apt-get install -y apt-transport-https gnupg curl lsb-release
# Instaleer Google cloud SDK
RUN export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
    echo "cloud SDK repo: $CLOUD_SDK_REPO" && \
    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    apt-get update -y && apt-get install google-cloud-sdk -y
# Instaleer Ansible en prereq
RUN pip3 install --upgrade pip; \
    pip3 install ansible; \
    pip install requests; \
    pip install google-auth; \
    pip install kubernetes; \
    pip install docker
# Instaleer Ansible-Galaxy packages
RUN ansible-galaxy collection install google.cloud; \
    ansible-galaxy collection install community.kubernetes; \
    ansible-galaxy collection install cloud.common
# Instaleer Kubectl
RUN apt-get install -y apt-transport-https ca-certificates curl gnupg; \
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list; \
    chmod 644 /etc/apt/sources.list.d/kubernetes.list; \
    apt-get install -y kubectl; \
    apt-get install google-cloud-sdk-gke-gcloud-auth-plugin -y
RUN apt-get update; \
    apt-get -y upgrade